name: build

on:
  push:
    branches:
      - '*'         # matches every branch
      - '*/*'       # matches every branch containing a single '/'
      - '!main'     # excludes main
      - '!staging'  # excludes staging

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: unfor19/install-aws-cli-action@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Build site
        run: |
          make _site

